name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t docker-image-pipeline .


    - name: Run the Docker image as Container
      run: docker run -it docker-image-pipeline

    - name: Finish Up
      run: echo 'finished..'
